# Generated by Django 5.1 on 2024-10-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='m4',
            new_name='m2',
        ),
    ]
