# Generated by Django 5.1 on 2024-10-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_m4_marks_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='total',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
